### ISSUE TITLE
zip file broken on Linux

### ISSUE THREAD

**Issue by xpd259** [pettersilie/FollowMeCar4X-Plane#1]
Hello, 
I'm not sure if it's just a Linux issues as I don't have windows at the moment
but the file-names are lacking folders
is the file name with the slashes in the file name and it just drops them all in one folder 

a picture is worth a thousand words so here's a screen shot

![screenshot_20160822_082331](https://cloud.githubusercontent.com/assets/822758/17846664/be2d1450-6841-11e6-9b21-f8f776c95a4a.png)

**Comment by pettersilie** [comment]
Hi Dick,


thanks for your message.

I am trying to work on this issue. Could you tell me, what kind of linux you are using?

Or is it a mac?


thanks

mirko


<http://aka.ms/weboutlook>


________________________________

**Comment by xpd259** [comment]
hiya @pettersilie 

I just tried it again deleting the old zip file and it seems to work now I must have just got a bad download that was cached by my network.

Thank you for this plug-in it is awesome as I'm limited by my plug-in options by choice of OS.

**Comment by pettersilie** [comment]
Allright!


Thanks for the good news. I also changed the uploaded ZIP after testing it on all possible linux, mac or windows platforms.


Have fun.

pet.


<http://aka.ms/weboutlook>


________________________________
